name: Build & Push Gatepass PHP Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Docker Hub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # GitHub Container Registry login
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/gatepass:8.2
            ${{ secrets.DOCKERHUB_USERNAME }}/gatepass:latest
            ghcr.io/${{ github.repository_owner || 'username' | toLowerCase }}/gatepass:8.2
            ghcr.io/${{ github.repository_owner || 'username' | toLowerCase }}/gatepass:latest
